export const dataColdHead = [
    ["Mounths", 'Temperatura(°K)'],
    ["Jan", 40],
    ["Fev", 42],
    ["Mar", 43],
    ["Abr", 44],
    ["Mai", 42],
    ["Jun", 44],
    ["Jul", 41],
    ["Ago", 40],
    ["Set", 41],
    ["Out", 42],
    ["Nov", 43],
    ["Dez", 45],
  ];