export const dataTemperature = [
    ["Mounths", 'Temperatura(°C)'],
    ["Jan", 25],
    ["Fev", 26],
    ["Mar", 23],
    ["Abr", 24],
    ["Mai", 22],
    ["Jun", 24],
    ["Jul", 21],
    ["Ago", 20],
    ["Set", 23],
    ["Out", 23],
    ["Nov", 25],
    ["Dez", 26],
  ];